// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int countG = 0;
		int countL = 0;
		while (N>0) {
			 if (Math.random()>0.5){
				countG++;
			 }
			 else{
				countL++;
			 }
			 N--;
			
		}
		
		System.out.println("> 0.5 " + countG + " times ");
		System.out.println("<= 0.5 " + countL + " times ");
		double ratio;
		if (countG>0 && countL>0){
			ratio = (double)countG/(double)countL;
			System.out.println(" Ratio: " + ratio);
		}
	}
}
